---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    k3s_url:          "{{ k3s_url           | default(omit) }}"
    k3s_token:        "{{ k3s_token         | default(omit) }}"
    node_labels:      "{{ node_labels       | default('env=edge') }}"
    agent_extra_args: "{{ agent_extra_args  | default('') }}"

    k3s_mode:          agent
    k3s_state:         installed
    k3s_become:        true
    k3s_server_url:    "{{ k3s_url }}"
    k3s_agent_extra_args: >
      --node-label {{ node_labels | replace(',', ' --node-label ') }}
      {{ agent_extra_args }}

  roles:
    - role: xanmanning.k3s