---
- name: Install and configure K3s server (control-plane)
  hosts: localhost
  become: true
  connection: local

  vars:
    # K3s configuration
    k3s_version: "v1.28.5+k3s1"
    environment: "{{ environment | default('prod') }}"
    server_extra_args: "{{ server_extra_args | default('') }}"
    k3s_server_config:
      disable:
        - traefik
      node-label:
        - "environment={{ environment }}"

  pre_tasks:
    - name: Update system packages (Debian/Ubuntu)
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update system packages (RHEL/CentOS/Amazon Linux)
      package:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install required packages
      package:
        name:
          - curl
          - wget
          - unzip
          - git
        state: present

  roles:
    - role: xanmanning.k3s
      vars:
        k3s_state: installed
        k3s_release_version: "{{ k3s_version }}"
        k3s_server: "{{ k3s_server_config }}"
        k3s_server_extra_args: "{{ server_extra_args }}"
        k3s_use_experimental: false

  post_tasks:
    - name: Wait for K3s API server to be ready
      wait_for:
        port: 6443
        host: 127.0.0.1
        timeout: 300 